# Generated by Django 2.2 on 2019-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meeting_date', models.CharField(max_length=30)),
                ('num_of_member', models.IntegerField(default=0)),
            ],
        ),
    ]
